# Generated by Django 4.2.15 on 2025-07-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_profile_account_currency_profile_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("bangladeshi_tk", "Bangladeshi Taka"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
    ]
