# Generated by Django 4.2.15 on 2025-07-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(
                choices=[
                    ("us_dollar", "US Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("bangladeshi_tk", "Bangladeshi Taka"),
                ],
                max_length=20,
                verbose_name="Currency",
            ),
        ),
    ]
